use std::sync::Arc;
use std::time::{Duration, Instant};

use serde::Deserialize;
use tokio::sync::RwLock;

use crate::config::OidcConfig;
use crate::discovery::{DiscoveryDocument, fetch_discovery};
use crate::error::OidcError;
use crate::id_token::{self, IdTokenClaims};
use crate::jwks::{Jwks, fetch_jwks};

/// Discovery documents change essentially never in practice — 24h just
/// bounds staleness after a real migration (e.g. issuer moving `jwks_uri`).
const DISCOVERY_TTL: Duration = Duration::from_secs(24 * 60 * 60);
/// JWKS rotates on a schedule the IdP controls; 1h is a reasonable default
/// bound between rotations, and an unknown `kid` forces an immediate refetch
/// regardless of this TTL (see `OidcClient::verify_id_token`).
const JWKS_TTL: Duration = Duration::from_secs(60 * 60);

struct Cached<T> {
    value: Arc<T>,
    fetched_at: Instant,
}

#[derive(Debug, Deserialize)]
pub struct TokenResponse {
    pub id_token: String,
    #[serde(default)]
    pub access_token: Option<String>,
    #[serde(default)]
    pub expires_in: Option<u64>,
}

/// Generic OIDC relying-party client: discovery + JWKS caching, PKCE-based
/// authorization-code flow, and ID-token verification. Nothing here assumes
/// Microsoft Entra ID specifically — `config.issuer_url` is whatever
/// OIDC-compliant authority the operator points it at.
pub struct OidcClient {
    config: OidcConfig,
    http: reqwest::Client,
    discovery: RwLock<Option<Cached<DiscoveryDocument>>>,
    jwks: RwLock<Option<Cached<Jwks>>>,
}

impl OidcClient {
    pub fn new(config: OidcConfig, http: reqwest::Client) -> Self {
        Self {
            config,
            http,
            discovery: RwLock::new(None),
            jwks: RwLock::new(None),
        }
    }

    pub fn config(&self) -> &OidcConfig {
        &self.config
    }

    /// Best-effort warmup for the discovery doc (and thus JWKS on first use).
    /// Call at boot so the *first real login* isn't the first time we learn
    /// the IdP is unreachable; failure here is logged by the caller and must
    /// not be fatal — a transient network hiccup at boot shouldn't crash the
    /// server, since discovery is retried lazily on the next login attempt.
    pub async fn warm(&self) -> Result<(), OidcError> {
        self.discovery_doc().await.map(|_| ())
    }

    async fn discovery_doc(&self) -> Result<Arc<DiscoveryDocument>, OidcError> {
        {
            let guard = self.discovery.read().await;
            if let Some(c) = guard.as_ref()
                && c.fetched_at.elapsed() < DISCOVERY_TTL
            {
                return Ok(c.value.clone());
            }
        }

        let doc = fetch_discovery(&self.http, &self.config.issuer_url).await?;

        // Defense-in-depth against a config mistake (not an attacker path —
        // we fetched this ourselves, over HTTPS, from `config.issuer_url`):
        // the discovery document's own `issuer` must agree with what the
        // operator configured, or every ID token this client ever validates
        // would be checked against a base the admin didn't actually intend.
        let normalize = |s: &str| s.trim_end_matches('/').to_string();
        if normalize(&doc.issuer) != normalize(&self.config.issuer_url) {
            return Err(OidcError::Discovery(format!(
                "discovery document issuer {:?} does not match configured OIDC_ISSUER_URL {:?}",
                doc.issuer, self.config.issuer_url
            )));
        }

        let arc = Arc::new(doc);
        let mut guard = self.discovery.write().await;
        *guard = Some(Cached { value: arc.clone(), fetched_at: Instant::now() });
        Ok(arc)
    }

    async fn jwks_doc(&self, force_refresh: bool) -> Result<Arc<Jwks>, OidcError> {
        if !force_refresh {
            let guard = self.jwks.read().await;
            if let Some(c) = guard.as_ref()
                && c.fetched_at.elapsed() < JWKS_TTL
            {
                return Ok(c.value.clone());
            }
        }

        let doc = self.discovery_doc().await?;
        let jwks = fetch_jwks(&self.http, &doc.jwks_uri).await?;
        let arc = Arc::new(jwks);
        let mut guard = self.jwks.write().await;
        *guard = Some(Cached { value: arc.clone(), fetched_at: Instant::now() });
        Ok(arc)
    }

    /// Build the authorization-endpoint redirect URL. `state`/`nonce` are
    /// generated by the caller (so it can persist them in short-lived cookies
    /// before redirecting) and echoed back for CSRF/replay protection.
    pub async fn authorization_url(
        &self,
        oauth_state: &str,
        nonce: &str,
        code_challenge: &str,
    ) -> Result<String, OidcError> {
        let doc = self.discovery_doc().await?;
        let mut url = reqwest::Url::parse(&doc.authorization_endpoint)
            .map_err(|e| OidcError::Discovery(format!("invalid authorization_endpoint: {e}")))?;
        url.query_pairs_mut()
            .append_pair("client_id", &self.config.client_id)
            .append_pair("response_type", "code")
            .append_pair("response_mode", "query")
            .append_pair("redirect_uri", &self.config.redirect_uri)
            .append_pair("scope", &self.config.scopes)
            .append_pair("state", oauth_state)
            .append_pair("nonce", nonce)
            .append_pair("code_challenge", code_challenge)
            .append_pair("code_challenge_method", "S256");
        Ok(url.into())
    }

    /// Exchange an authorization `code` (+ PKCE `code_verifier`) for tokens.
    pub async fn exchange_code(
        &self,
        code: &str,
        code_verifier: &str,
    ) -> Result<TokenResponse, OidcError> {
        let doc = self.discovery_doc().await?;
        let params = [
            ("grant_type", "authorization_code"),
            ("code", code),
            ("redirect_uri", self.config.redirect_uri.as_str()),
            ("client_id", self.config.client_id.as_str()),
            ("client_secret", self.config.client_secret.as_str()),
            ("code_verifier", code_verifier),
        ];
        let resp = self
            .http
            .post(&doc.token_endpoint)
            .form(&params)
            .send()
            .await
            .map_err(|e| OidcError::TokenExchange(e.to_string()))?;

        if !resp.status().is_success() {
            let status = resp.status();
            return Err(OidcError::TokenExchange(format!("token endpoint returned {status}")));
        }
        resp.json::<TokenResponse>()
            .await
            .map_err(|e| OidcError::TokenExchange(e.to_string()))
    }

    /// Verify an `id_token`. On an unrecognized `kid` the JWKS cache is
    /// force-refreshed exactly once and verification retried — this is the
    /// normal path for routine IdP key rotation, not an error condition.
    pub async fn verify_id_token(
        &self,
        raw_id_token: &str,
        expected_nonce: &str,
    ) -> Result<IdTokenClaims, OidcError> {
        let doc = self.discovery_doc().await?;
        let jwks = self.jwks_doc(false).await?;
        match id_token::verify(raw_id_token, &jwks, &doc.issuer, &self.config.client_id, expected_nonce) {
            Err(OidcError::UnknownKid(_)) => {
                let refreshed = self.jwks_doc(true).await?;
                id_token::verify(raw_id_token, &refreshed, &doc.issuer, &self.config.client_id, expected_nonce)
            }
            other => other,
        }
    }
}
