[package]
name = "nasiko-gateway"
edition.workspace = true
version.workspace = true

[[bin]]
name = "nasiko-gateway"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
nasiko-auth.workspace = true

# Pingora
pingora = { version = "0.8", features = ["proxy", "lb", "openssl"] }
pingora-core = "0.8"
pingora-proxy = "0.8"
pingora-http = "0.8"
pingora-limits = "0.8"

# Serialization & config
serde = { workspace = true }
serde_json = { workspace = true }

# Utilities
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
chrono = { workspace = true }
dashmap = { workspace = true }
bytes = { workspace = true }
http = { workspace = true }
async-trait = "0.1"

[dev-dependencies]
tokio = { workspace = true }
