//! Offline vector‑similarity request classifier.
//
// This is a placeholder implementation that currently falls back to the existing
// regex classifier. The design goal is to provide a primary classifier that does
// **not** perform any external network calls. In the future this module can be
// expanded to load pre‑computed embeddings from a local store and compute cosine
// similarity with a query embedding generated by the router's local embedding
// function.

use super::classifier::{ClassifyInput, Classification, ClassifyError, RequestClassifier};
use async_trait::async_trait;

#[derive(Debug, Default, Clone, Copy)]
pub struct VectorSimilarityClassifier;

#[async_trait]
impl RequestClassifier for VectorSimilarityClassifier {
    fn name(&self) -> &str {
        "vector"
    }

    async fn classify(&self, input: &ClassifyInput<'_>) -> Result<Classification, ClassifyError> {
        // Placeholder: use the same regex classification logic.
        // Replace this with a real vector‑search when embeddings are available.
        Ok(super::regex_classification(input.query))
    }
}
