[package]
name = "nasiko-runtime"
edition.workspace = true
version.workspace = true

[dependencies]
tokio = { workspace = true }
async-trait = "0.1"
thiserror = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }

# docker feature
bollard = { version = "0.17", optional = true }
bytes = { workspace = true, optional = true }
futures-util = { version = "0.3", optional = true }
serde_json = { workspace = true, optional = true }

[features]
default = ["docker"]
docker = ["dep:bollard", "dep:bytes", "dep:futures-util", "dep:serde_json"]
simulated = []

[dev-dependencies]
serde_json = { workspace = true }
uuid = { workspace = true }