use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MafStep {
    pub step_id: Uuid,
    pub step_index: i32,
    pub agent_id: Uuid,
    pub agent_name: String,
    pub agent_endpoint: String,
    /// What this step should accomplish — used by the runtime planner to generate
    /// the actual prompt and extraction goal at execution time (Python MAF parity).
    pub task_description: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MafDefinition {
    /// Overall description of the workflow — fed to the runtime planner.
    #[serde(default)]
    pub description: Option<String>,
    pub steps: Vec<MafStep>,
    /// Guidelines for synthesising the final user-facing answer from all step outputs.
    #[serde(default)]
    pub output_generation: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StepResult {
    pub step_id: Uuid,
    pub step_index: i32,
    pub agent_id: Uuid,
    pub agent_name: String,
    /// "pending" | "running" | "success" | "failed" — updated and persisted
    /// incrementally as the step progresses, so polling the execution shows
    /// live status rather than just the final outcome.
    #[serde(default = "default_pending_status")]
    pub status: String,
    /// Set only when status = "failed".
    #[serde(default)]
    pub error: Option<String>,
    /// The prompt template with placeholders, generated by plan_execution.
    pub prompt_template: String,
    /// The extraction goal for this step, generated by plan_execution.
    pub to_extract: String,
    /// The actual prompt sent to the agent after placeholder substitution.
    pub prompt: String,
    pub extracted_info: Option<String>,
    pub tokens_used: i64,
    pub latency_ms: i64,
    pub context: Option<String>,
    pub obs_logs: serde_json::Value,
}

fn default_pending_status() -> String {
    "pending".to_string()
}

pub struct ExecutionResult {
    pub output: String,
    pub step_results: Vec<StepResult>,
    pub tokens_used: i64,
}
