server {
    listen 4010;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location /metrics/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
