// Execution history fixtures — GET /api/observability/session/list
// (SessionListResponse in oss/server/src/observability/service.rs; see /api/docs).
export default {
  fetch: [
    [{ method: "GET", path: /^\/api\/observability\/session\/list/ }, {
      data: {
        sessions: [
          {
            id: "cHJvamVjdDox",
            session_id: "ses_18a5801d3353463ca39ebc216887f385",
            agent_id: "orchestrator",
            num_traces: 1,
            start_time: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
            end_time: new Date(Date.now() - 39 * 60 * 1000).toISOString(),
            duration_ms: 15620,
            first_input: "Hello, what can you do?",
            last_output: "Hello! I'm an orchestrator that can help you...",
            token_usage: { total: 6705 },
            trace_latency_ms_p50: 15620,
            trace_latency_ms_p99: 15620,
            cost_summary: { total: { cost: 0.001 } },
            session_annotations: [],
            session_annotation_summaries: [],
          },
          {
            id: "cHJvamVjdDoy",
            session_id: "ses_77b2f4c09a1e4d2c8f5a3b6d9e0c1a2b",
            agent_id: "coding-agent",
            num_traces: 4,
            start_time: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
            end_time: new Date(Date.now() - 2.8 * 3600 * 1000).toISOString(),
            duration_ms: 74100,
            first_input: "Fix the DNS resolution issue",
            last_output: "Fixed the DNS resolution issue in the container networking layer",
            token_usage: { total: 29706 },
            trace_latency_ms_p50: 8210,
            trace_latency_ms_p99: 31500,
            cost_summary: { total: { cost: 0.166 } },
            session_annotations: [],
            session_annotation_summaries: [],
          },
          {
            id: "cHJvamVjdDoz",
            session_id: "ses_41c6d2e88f0b4a719c3d5e7f2a8b9c0d",
            agent_id: "research-agent",
            num_traces: 2,
            start_time: new Date(Date.now() - 26 * 3600 * 1000).toISOString(),
            end_time: new Date(Date.now() - 25.9 * 3600 * 1000).toISOString(),
            duration_ms: 22040,
            first_input: "Summarize Kubernetes operator patterns",
            last_output: "Here's the summary of Kubernetes operator patterns...",
            token_usage: { total: 12180 },
            trace_latency_ms_p50: 10930,
            trace_latency_ms_p99: 11110,
            cost_summary: { total: { cost: 0.054 } },
            session_annotations: [],
            session_annotation_summaries: [],
          },
        ],
        total_agents: 3,
        successful_agents: 3,
        pagination: { end_cursor: null, has_next_page: false },
      },
    }],
  ],
};
